instrumentation:
    include-all-sources: true
    excludes:
        - examples/*
reporting:
    print: detail
    reports:
        - cobertura
        - lcov
        - html
check:
    global:
        statements: 100
        lines: 100
        branches: 100
        functions: 100
